app:
  serviceAccount:
    enabled: true
  name: bff
  image:
    repository: "onecx/onecx-data-orchestrator-bff"
  envCustom:
    - name: QUARKUS_KUBERNETES_CLIENT_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
  operator:
    # Permission
    permission:
      enabled: true
      spec:
        permissions:
          crd:
            read: permission on all GET requests and POST search
            write: permission on PUT, POST, PATCH requests, where objects are saved or updated
            touch: permission on PUT request, where a resource is touched
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            defaultClientScopes: [ ocx-pm:read ]