---
openapi: 3.0.3
info:
  title: onecx-data-orchestrator-bff
  description: OneCX Data Orchestrator BFF
  version: 1.0.0
  contact:
    email: "tkit_dev@1000kit.org"
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: "http://onecx-data-orchestrator-bff:8080"
tags:
  - name: data
paths:
  /data/{id}:
    get:
      x-onecx:
        permissions:
          data:
            - read
      tags:
        - data
      description: get data by id
      operationId: getDataById
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        "200":
          description: OK
        "404":
          description: NOT FOUND
        "400":
          description: BAD REQUEST
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
components:
  schemas:
    OffsetDateTime:
      format: date-time
      type: string
      example: 2022-03-10T12:15:50-04:00
    ProblemDetailResponse:
      type: object
      properties:
        errorCode:
          type: string
        detail:
          type: string
        params:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailParam'
        invalidParams:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailInvalidParam'
    ProblemDetailParam:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    ProblemDetailInvalidParam:
      type: object
      properties:
        name:
          type: string
        message:
          type: string
  parameters:
    id:
      name: id
      in: path
      required: true
      schema:
        type: string

